// generated by Textmapper; DO NOT EDIT

package ast

import (
	"github.com/inspirer/textmapper/tm-go/parsers/test"
	"github.com/inspirer/textmapper/tm-go/parsers/test/selector"
)

type Node interface {
	Type() test.NodeType
	Offset() int
	Endoffset() int
	// Child returns the first child node that matches the selector.
	Child(sel selector.Selector) Node
	Children(sel selector.Selector) []Node
	// Next returns the first element among the following siblings that matches the selector.
	Next(sel selector.Selector) Node
	// NextAll returns all following siblings of the node that match the selector.
	NextAll(sel selector.Selector) []Node
	Text() string
	IsValid() bool
}

// Interfaces.

type TestNode interface {
	TestNode() Node
}

type Token struct {
	Node
}

type NilNode struct{}

var nilInstance = &NilNode{}

// All types implement TestNode.
func (n AsExpr) TestNode() Node        { return n.Node }
func (n Block) TestNode() Node         { return n.Node }
func (n Decl1) TestNode() Node         { return n.Node }
func (n Decl2) TestNode() Node         { return n.Node }
func (n Empty1) TestNode() Node        { return n.Node }
func (n EvalFoo) TestNode() Node       { return n.Node }
func (n EvalFoo2) TestNode() Node      { return n.Node }
func (n Icon) TestNode() Node          { return n.Node }
func (n Int) TestNode() Node           { return n.Node }
func (n IntExpr) TestNode() Node       { return n.Node }
func (n LastInt) TestNode() Node       { return n.Node }
func (n Negation) TestNode() Node      { return n.Node }
func (n PlusExpr) TestNode() Node      { return n.Node }
func (n Test) TestNode() Node          { return n.Node }
func (n TestClause) TestNode() Node    { return n.Node }
func (n TestIntClause) TestNode() Node { return n.Node }
func (n Int7) TestNode() Node          { return n.Node }
func (n Int9) TestNode() Node          { return n.Node }
func (n Token) TestNode() Node         { return n.Node }
func (NilNode) TestNode() Node         { return nil }

type Declaration interface {
	TestNode
	declarationNode()
}

// declarationNode() ensures that only the following types can be
// assigned to Declaration.
//
func (AsExpr) declarationNode()        {}
func (Block) declarationNode()         {}
func (Decl1) declarationNode()         {}
func (Decl2) declarationNode()         {}
func (Empty1) declarationNode()        {}
func (EvalFoo) declarationNode()       {}
func (EvalFoo2) declarationNode()      {}
func (Int) declarationNode()           {}
func (IntExpr) declarationNode()       {}
func (LastInt) declarationNode()       {}
func (PlusExpr) declarationNode()      {}
func (TestClause) declarationNode()    {}
func (TestIntClause) declarationNode() {}
func (NilNode) declarationNode()       {}

type Expr interface {
	TestNode
	exprNode()
}

// exprNode() ensures that only the following types can be
// assigned to Expr.
//
func (AsExpr) exprNode()   {}
func (IntExpr) exprNode()  {}
func (PlusExpr) exprNode() {}
func (NilNode) exprNode()  {}

// Types.

type AsExpr struct {
	Node
}

func (n AsExpr) Left() Expr {
	return ToTestNode(n.Child(selector.Expr)).(Expr)
}

func (n AsExpr) Right() Expr {
	return ToTestNode(n.Child(selector.Expr).Next(selector.Expr)).(Expr)
}

type Block struct {
	Node
}

func (n Block) Negation() (Negation, bool) {
	field := Negation{n.Child(selector.Negation)}
	return field, field.IsValid()
}

func (n Block) Declaration() []Declaration {
	nodes := n.Children(selector.Declaration)
	var ret = make([]Declaration, 0, len(nodes))
	for _, node := range nodes {
		ret = append(ret, ToTestNode(node).(Declaration))
	}
	return ret
}

type Decl1 struct {
	Node
}

func (n Decl1) Identifier() []Token {
	nodes := n.Children(selector.Identifier)
	var ret = make([]Token, 0, len(nodes))
	for _, node := range nodes {
		ret = append(ret, Token{node})
	}
	return ret
}

type Decl2 struct {
	Node
}

type Empty1 struct {
	Node
}

type EvalFoo struct {
	Node
}

func (n EvalFoo) Expr() Expr {
	return ToTestNode(n.Child(selector.Expr)).(Expr)
}

type EvalFoo2 struct {
	Node
}

func (n EvalFoo2) A() Expr {
	return ToTestNode(n.Child(selector.Expr)).(Expr)
}

func (n EvalFoo2) B() Expr {
	return ToTestNode(n.Child(selector.Expr).Next(selector.Expr)).(Expr)
}

type Icon struct {
	Node
}

type Int struct {
	Node
}

type IntExpr struct {
	Node
}

type LastInt struct {
	Node
}

type Negation struct {
	Node
}

type PlusExpr struct {
	Node
}

func (n PlusExpr) Left() Expr {
	return ToTestNode(n.Child(selector.Expr)).(Expr)
}

func (n PlusExpr) Right() Expr {
	return ToTestNode(n.Child(selector.Expr).Next(selector.Expr)).(Expr)
}

type Test struct {
	Node
}

func (n Test) Declaration() []Declaration {
	nodes := n.Children(selector.Declaration)
	var ret = make([]Declaration, 0, len(nodes))
	for _, node := range nodes {
		ret = append(ret, ToTestNode(node).(Declaration))
	}
	return ret
}

type TestClause struct {
	Node
}

type TestIntClause struct {
	Node
}

func (n TestIntClause) Icon() Icon {
	return Icon{n.Child(selector.Icon)}
}

type Int7 struct {
	Node
}

type Int9 struct {
	Node
}
