// generated by Textmapper; DO NOT EDIT

package json

import (
	"fmt"
)

type NodeType int

type Listener func(t NodeType, offset, endoffset int)

const (
	NoType NodeType = iota
	JSONText
	JSONValue
	EmptyObject
	JSONObject
	JSONMember
	JSONArray
	NonExistingType
	MultiLineComment
	InvalidToken
	JsonString
	NodeTypeMax
)

var nodeTypeStr = [...]string{
	"NONE",
	"JSONText",
	"JSONValue",
	"EmptyObject",
	"JSONObject",
	"JSONMember",
	"JSONArray",
	"NonExistingType",
	"MultiLineComment",
	"InvalidToken",
	"JsonString",
}

func (t NodeType) String() string {
	if t >= 0 && int(t) < len(nodeTypeStr) {
		return nodeTypeStr[t]
	}
	return fmt.Sprintf("node(%d)", t)
}
