// generated by Textmapper; DO NOT EDIT

package json

import (
	"fmt"
)

// Token is an enum of all terminal symbols of the json language.
type Token int

// Token values.
const (
	UNAVAILABLE Token = iota - 1
	EOI
	INVALID_TOKEN
	LBRACE // {
	RBRACE // }
	LBRACK // [
	RBRACK // ]
	COLON  // :
	COMMA  // ,
	SPACE
	MULTILINECOMMENT
	JSONSTRING
	JSONNUMBER
	ID
	NULL   // null
	TRUE   // true
	FALSE  // false
	CHAR_A // A
	CHAR_B // B
	ERROR

	NumTokens
)

var tokenStr = [...]string{
	"EOI",
	"INVALID_TOKEN",
	"{",
	"}",
	"[",
	"]",
	":",
	",",
	"SPACE",
	"MULTILINECOMMENT",
	"JSONSTRING",
	"JSONNUMBER",
	"ID",
	"null",
	"true",
	"false",
	"A",
	"B",
	"ERROR",
}

func (tok Token) String() string {
	if tok >= 0 && int(tok) < len(tokenStr) {
		return tokenStr[tok]
	}
	return fmt.Sprintf("token(%d)", tok)
}
