#!/bin/sh

ant clean deploy go

go fmt ../tm-go/parsers/... ../tm-parsers/...
go test ../tm-go/parsers/json/... ../tm-go/parsers/test/... ../tm-parsers/tm/... ../tm-parsers/js/... ../tm-parsers/parsertest/... ../tm-go/parsers/tm/...
